services:
  # Main trading system using existing infrastructure
  trading-system:
    build: .
    container_name: ultimate-trading-system
    environment:
      - REDIS_URL=redis://tyree-redis:6379
      - DATABASE_URL=postgresql://trading_user:trading_password@tyree-postgres:5432/trading_agents
      - ALPACA_API_KEY=${ALPACA_API_KEY:-your_alpaca_api_key_here}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY:-your_alpaca_secret_key_here}
      - TRADING_MODE=${TRADING_MODE:-PAPER}
      - LOG_LEVEL=INFO
      - NUM_AGENTS=11
      - DATA_UPDATE_INTERVAL=30
      - EVALUATION_INTERVAL=300
      - MCP_ENABLED=false
      - DYNAMIC_CONFIG_ENABLED=true
      - SAFE_MODE_SWITCHING=true
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: ["python", "run_trading_system.py"]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    networks:
      - default
      - tyree-systems_tyree-network

networks:
  tyree-systems_tyree-network:
    external: true
