services:
  # Basic services first
  redis:
    image: redis:7-alpine
    container_name: ultimate-trading-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: ultimate-trading-postgres
    environment:
      POSTGRES_DB: trading_agents
      POSTGRES_USER: trading_user
      POSTGRES_PASSWORD: trading_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Start with just Gordon Assistant first
  gordon-assistant:
    build:
      context: ./mcp_models/gordon
      dockerfile: Dockerfile
    container_name: mcp-gordon
    ports:
      - "8001:8001"
    environment:
      - MODEL_NAME=gordon_assistant
      - PORT=8001
      - LOG_LEVEL=INFO
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Main trading system
  trading-system:
    build: .
    container_name: ultimate-trading-system
    depends_on:
      - redis
      - postgres
      - gordon-assistant
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://trading_user:trading_password@postgres:5432/trading_agents
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY}
      - ALPACA_BASE_URL=https://paper-api.alpaca.markets
      - MCP_ENABLED=true
      - MCP_GORDON_URL=http://gordon-assistant:8001
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: ["python", "run_trading_system_no_mcp.py"]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # MCP Dashboard
  mcp-dashboard:
    build: .
    container_name: mcp-dashboard
    ports:
      - "8008:8008"
    environment:
      - MCP_GORDON_URL=http://gordon-assistant:8001
    volumes:
      - ./mcp_dashboard:/app/mcp_dashboard
    restart: unless-stopped
    command: ["python", "mcp_dashboard_simple.py"]

volumes:
  redis_data:
  postgres_data:
