version: '3.8'

services:
  trading-system:
    build: .
    container_name: competitive-trading-agents
    environment:
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
      - APCA_API_BASE_URL=https://paper-api.alpaca.markets
      - TRADING_MODE=PAPER
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    cpus: '4'
    mem_limit: 2g
    networks:
      - trading-net

  redis:
    image: redis:7-alpine
    container_name: trading-redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    cpus: '1'
    mem_limit: 512m
    networks:
      - trading-net

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: trading-db
    environment:
      - POSTGRES_DB=trading_data
      - POSTGRES_USER=trading_user
      - POSTGRES_PASSWORD=secure_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    cpus: '2'
    mem_limit: 1g
    networks:
      - trading-net

volumes:
  redis_data:
  postgres_data:

networks:
  trading-net:
    driver: bridge